# Base configs
baseurl: "https://photos.alhuff.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photos | Austin Lynn Huffman"
subtitle: "See the world through my eyes!"
author: "Austin Lynn Huffman"
header:
 title: "Photos"
 subtitle: "by Austin Lynn Huffman"
footer:
 name: "Hey there, my name is Austin"
 bio: "I'm an info tech student who loves cars and photography!"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/alhuff_"
  linkedin: "https://in.linkedin.com/in/austinlynnhuffman"
  github: "https://www.github.com/jellayy"
